"use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { saveProjectAction,type ProjectInput } from "@/app/actions/projects";
import type { ProjectDTO } from "@/lib/project-service";
const slug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export default function ProjectForm({mode,project,companies}:{mode:"create"|"edit";project?:ProjectDTO;companies:{id:string;name:string}[]}){
 const router=useRouter();const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [form,setForm]=useState<ProjectInput>({name:project?.name??"",slug:project?.slug??"",companyId:project?.companyId??companies[0]?.id??"",category:project?.category??"",status:project?.status??"Draft",summary:project?.summary??"",description:project?.description??"",coverImage:project?.coverImage??"",coverImageAlt:project?.coverImageAlt??"",featured:project?.featured??false,tags:project?.tags??[],location:project?.location??"",startDate:project?.startDate?.slice(0,10)??"",completionDate:project?.completionDate?.slice(0,10)??"",displayOrder:project?.displayOrder??0,seoTitle:project?.seoTitle??"",seoDescription:project?.seoDescription??""});
 const set=<K extends keyof ProjectInput>(key:K,value:ProjectInput[K])=>setForm(current=>({...current,[key]:value}));
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");const result=await saveProjectAction(project?.id??null,{...form,slug:slug(form.slug)});if(!result.ok){setError(result.error);setSaving(false);return;}router.push(`/admin/projects/${result.id}`);router.refresh();}
 return <div className="admin-project-form-page"><div className="admin-form-page__header"><div><Link href="/admin/projects">← Back to Projects</Link><p>Project Management</p><h2>{mode==="create"?"Create New Project":`Edit ${project?.name}`}</h2></div></div><form className="admin-project-form" onSubmit={submit}>{error&&<div className="admin-form-error">{error}</div>}<section className="admin-form-section"><div className="admin-form-section__heading"><span>01</span><div><h3>Project information</h3><p>Identity, ownership, publishing and public content.</p></div></div><div className="admin-form-grid">
 {([["name","Project name"],["slug","Slug"],["category","Category"],["location","Location"],["coverImage","Cover image URL"],["coverImageAlt","Image alternative text"],["seoTitle","SEO title"],["seoDescription","SEO description"]] as const).map(([key,label])=><label className="admin-form-field" key={key}><span>{label}</span><input value={String(form[key])} onChange={e=>set(key,key==="slug"?slug(e.target.value):e.target.value)} required={["name","slug","category"].includes(key)}/></label>)}
 <label className="admin-form-field"><span>Company</span><select value={form.companyId} onChange={e=>set("companyId",e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="admin-form-field"><span>Status</span><select value={form.status} onChange={e=>set("status",e.target.value as ProjectInput["status"])}><option>Draft</option><option>Published</option><option>Archived</option></select></label><label className="admin-form-field"><span>Display order</span><input type="number" min="0" value={form.displayOrder} onChange={e=>set("displayOrder",Number(e.target.value))}/></label><label className="admin-form-field"><span>Start date</span><input type="date" value={form.startDate} onChange={e=>set("startDate",e.target.value)}/></label><label className="admin-form-field"><span>Completion date</span><input type="date" value={form.completionDate} onChange={e=>set("completionDate",e.target.value)}/></label><label className="admin-form-field admin-form-field--full"><span>Summary</span><textarea rows={4} value={form.summary} onChange={e=>set("summary",e.target.value)} required/></label><label className="admin-form-field admin-form-field--full"><span>Description</span><textarea rows={9} value={form.description} onChange={e=>set("description",e.target.value)} required/></label><label className="admin-form-field admin-form-field--full"><span>Tags (comma separated)</span><input value={form.tags.join(", ")} onChange={e=>set("tags",e.target.value.split(",").map(v=>v.trim()).filter(Boolean))}/></label><label className="admin-checkbox-field"><input type="checkbox" checked={form.featured} onChange={e=>set("featured",e.target.checked)}/><span><strong>Featured project</strong></span></label></div></section><div className="admin-form-actions"><Link className="admin-secondary-button" href="/admin/projects">Cancel</Link><button className="admin-primary-button" disabled={saving}>{saving?"Saving…":"Save Project"}</button></div></form></div>;
}
