/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import type { PublicTeam } from "@/lib/team-mapping";
import TeamMotion from "./TeamMotion";
import PortraitImage from "./PortraitImage";
import styles from "./team.module.css";

export function Portrait({ photo, name, priority = false }: { photo: string; name: string; priority?: boolean }) {
  const fallback = <div className={styles.monogram} aria-label={`${name} portrait not provided`}><span aria-hidden="true">{name.split(/\s+/).slice(0, 2).map(n => n[0]).join("")}</span><small>BCU GROUP</small></div>;
  return photo ? <div className={styles.portraitShell}><PortraitImage src={photo} alt={name} priority={priority} />{fallback}</div> : fallback;
}
function Text({ value }: { value: string }) { return <div className={styles.prose}>{value.split(/\n\s*\n/).filter(Boolean).map((p, i) => <p key={i}>{p}</p>)}</div>; }
function Timeline({ title, id, rows }: { title: string; id: string; rows: PublicTeam["experience"] }) {
  if (!rows.length) return null;
  return <section id={id} className={styles.chapter} data-reveal><div className={styles.chapterHeading}><span className={styles.kicker}>{title}</span><h2>{title === "Leadership" ? "Building with purpose." : title}</h2></div><div className={styles.timeline}>{rows.map((r, i) => <article key={i}><span>{r.period || String(i + 1).padStart(2, "0")}</span><div><h3>{r.title}</h3>{r.organisation && <p className={styles.gold}>{r.organisation}</p>}{r.description && <Text value={r.description} />}</div></article>)}</div></section>;
}
function Chapters({ member: m }: { member: PublicTeam }) {
  const links = [{ label: "LinkedIn", url: m.linkedinUrl }, { label: "GitHub", url: m.githubUrl }, { label: "Website", url: m.websiteUrl }, ...m.otherSocialLinks].filter(s => s.url);
  return <>
    {m.biography && <section id="about" className={styles.chapter} data-reveal><div className={styles.chapterHeading}><span className={styles.kicker}>The person behind the purpose</span><h2>About.</h2></div><Text value={m.biography} /></section>}
    <Timeline id="leadership" title="Leadership" rows={m.leadership} />
    {m.technology && <section id="technology" className={`${styles.chapter} ${styles.technology}`} data-reveal><div className={styles.chapterHeading}><span className={styles.kicker}>Technology & development</span><h2>Ideas into<br /><em>possibility.</em></h2></div><Text value={m.technology} /></section>}
    {m.portfolioProjects.length > 0 && <section id="work" className={styles.work} data-reveal><div className={styles.chapterHeading}><span className={styles.kicker}>Projects & systems</span><h2>Selected work.</h2></div><div className={styles.projectGrid}>{m.portfolioProjects.map((p, i) => <article className={styles.project} key={i} data-reveal>{p.image && <img src={p.image} alt={p.name} width={900} height={600} loading="lazy" />}<div className={styles.projectCopy}><span className={styles.kicker}>{String(i + 1).padStart(2, "0")} / {p.category}</span><h3>{p.name}</h3>{p.role && <p className={styles.gold}>{p.role}</p>}{p.description && <Text value={p.description} />}<ul className={styles.tags}>{p.technologies.map((t, j) => <li key={j}>{t}</li>)}</ul>{p.link && <a href={p.link} className={styles.textLink} rel={p.link.startsWith("http") ? "noopener noreferrer" : undefined}>Explore project <span aria-hidden="true">↗</span></a>}</div></article>)}</div></section>}
    {(m.skills.length > 0 || m.expertise.length > 0) && <section id="capabilities" className={styles.chapter} data-reveal><div className={styles.chapterHeading}><span className={styles.kicker}>Skills & expertise</span><h2>Capabilities.</h2></div><div>{m.skills.length > 0 && <><h3>Skills</h3><ul className={styles.tags}>{m.skills.map((s, i) => <li key={i}>{s}</li>)}</ul></>}{m.expertise.length > 0 && <><h3>Expertise</h3><ul className={styles.tags}>{m.expertise.map((s, i) => <li key={i}>{s}</li>)}</ul></>}</div></section>}
    <Timeline id="experience" title="Experience" rows={m.experience} /><Timeline id="achievements" title="Achievements" rows={m.achievements} /><Timeline id="education" title="Education" rows={m.education} />
    {m.vision && <section id="vision" className={styles.vision} data-reveal><span className={styles.kicker}>Vision & philosophy</span><Text value={m.vision} /></section>}
    {(links.length > 0 || m.email || m.phone || m.location) && <section id="connect" className={styles.chapter} data-reveal><div className={styles.chapterHeading}><span className={styles.kicker}>Contact & connect</span><h2>Start a<br /><em>conversation.</em></h2></div><div className={styles.connect}>{m.email && <a href={`mailto:${m.email}`}>{m.email} ↗</a>}{m.phone && <a href={`tel:${m.phone.replace(/[^+\d]/g, "")}`}>{m.phone}</a>}{m.location && <p>{m.location}</p>}{links.map((l, i) => <a key={i} href={l.url} rel="noopener noreferrer">{l.label} ↗</a>)}</div></section>}
  </>;
}
export default function TeamProfile({ member: m }: { member: PublicTeam }) {
  const founder = m.profileType === "FOUNDER_PORTFOLIO";
  if (!founder) return <div className={`${styles.team} ${styles.standard}`} data-testid="standard-profile"><div className={styles.wrap}><Link href="/team" className={styles.textLink}>← Our Team</Link><header className={styles.standardHero}><div className={styles.photoFrame}><Portrait photo={m.photo} name={m.name} priority /></div><div><p className={styles.kicker}>{m.company || "BCU Group"}{m.department ? ` / ${m.department}` : ""}</p><h1>{m.name}</h1><p className={styles.role}>{m.title}</p>{m.secondaryTitle && <p className={styles.gold}>{m.secondaryTitle}</p>}{m.shortBio && <p className={styles.lead}>{m.shortBio}</p>}</div></header><Chapters member={m} /></div></div>;
  const nav = [{ id: "about", label: "About", show: m.biography }, { id: "leadership", label: "Leadership", show: m.leadership.length }, { id: "technology", label: "Technology", show: m.technology }, { id: "work", label: "Work", show: m.portfolioProjects.length }, { id: "capabilities", label: "Capabilities", show: m.skills.length || m.expertise.length }, { id: "vision", label: "Vision", show: m.vision }].filter(n => n.show);
  return <div className={`${styles.team} ${styles.founder}`} data-testid="founder-portfolio"><TeamMotion><div className={styles.wrap}><div className={styles.portfolioBar}><Link href="/team">← Our Team</Link><span>BCU / FOUNDER PORTFOLIO</span><span className={styles.gold}>Ideas. Leadership. Impact.</span></div><header className={styles.founderHero}><div className={styles.heroCopy}><p className={styles.kicker}>{m.company || "BCU Group"}{m.department ? ` / ${m.department}` : ""}</p><h1>{m.name.split(" ").map((word, i) => <span key={i}>{word} </span>)}</h1><div className={styles.heroDetails}><p className={styles.role}>{m.title}</p>{m.secondaryTitle && <p className={styles.gold}>{m.secondaryTitle}</p>}{m.shortBio && <p className={styles.lead}>{m.shortBio}</p>}</div>{nav.length > 0 && <a href={`#${nav[0].id}`} className={styles.roundLink}>Explore the story <span aria-hidden="true">↓</span></a>}</div><div className={styles.founderPortrait}><Portrait photo={m.photo} name={m.name} priority /><span className={styles.portraitMark}>BCU / {m.title}</span></div><div className={styles.orbit} aria-hidden="true" /></header>{nav.length > 0 && <nav aria-label="Portfolio sections" className={styles.sectionNav}>{nav.map((n, i) => <a key={n.id} href={`#${n.id}`}><small>{String(i + 1).padStart(2, "0")}</small>{n.label}</a>)}</nav>}<Chapters member={m} /><div className={styles.signature}><span>{m.name}</span><Link href="/team">Meet the team ↗</Link></div></div></TeamMotion></div>;
}
