import Link from "next/link";
import { prisma } from "@/lib/prisma";
import TeamControls from "@/components/admin/TeamControls";
export default async function TeamManagement({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; type?: string }> }) {
  const filters = await searchParams;
  const q = typeof filters.q === "string" ? filters.q.slice(0, 120) : "";
  const members = await prisma.teamMember.findMany({ where: {
    ...(q ? { OR: ["name", "title", "company", "department"].map(key => ({ [key]: { contains: q, mode: "insensitive" as const } })) } : {}),
    ...(filters.status === "published" ? { published: true } : filters.status === "hidden" ? { published: false } : {}),
    ...(["STANDARD", "FOUNDER_PORTFOLIO"].includes(filters.type || "") ? { profileType: filters.type as "STANDARD" | "FOUNDER_PORTFOLIO" } : {}),
  }, orderBy: [{ displayOrder: "asc" }, { name: "asc" }, { id: "asc" }], select: { id: true, name: true, title: true, published: true, displayOrder: true, profileType: true } });
  return <div className="admin-news-form"><div className="admin-news-form__header"><div><p>People & leadership</p><h1>Our Team</h1><p>Manage profiles, visibility and the order shown on the website.</p></div><Link href="/admin/team/new" className="admin-primary-button">Add team member</Link></div><form className="admin-form-card"><div className="admin-form-grid"><label className="admin-form-field"><span>Search team</span><input name="q" defaultValue={q} placeholder="Name, title, company or department" /></label><label className="admin-form-field"><span>Status</span><select aria-label="Status" name="status" defaultValue={filters.status || ""}><option value="">All statuses</option><option value="published">Published</option><option value="hidden">Hidden</option></select></label><label className="admin-form-field"><span>Profile type</span><select aria-label="Profile type" name="type" defaultValue={filters.type || ""}><option value="">All profiles</option><option value="STANDARD">Standard</option><option value="FOUNDER_PORTFOLIO">Founder portfolio</option></select></label></div><button className="admin-secondary-button">Filter team</button> <Link href="/admin/team">Clear filters</Link></form><p>{members.length} team member{members.length !== 1 ? "s" : ""}</p>{members.map(member => <article key={member.id} className="admin-form-card"><h2><Link href={`/admin/team/${member.id}`}>{member.name}</Link></h2><p>{member.title} · {member.published ? "Published" : "Hidden"} · {member.profileType === "STANDARD" ? "Standard" : "Founder portfolio"}</p><p><Link href={`/admin/team/${member.id}`}>View</Link> · <Link href={`/admin/team/${member.id}/edit`}>Edit</Link></p><TeamControls {...member} /></article>)}{!members.length && <p>No team members match these filters.</p>}</div>;
}
