import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { emailSchema, safeUrlSchema } from "@/lib/validation";
import { deleteFile, uploadFile } from "@/lib/storage";
export const runtime="nodejs";
const allowed=new Set(["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"]);
const fields=z.object({careerId:z.string().cuid(),applicantName:z.string().trim().min(2).max(100),email:emailSchema,phone:z.string().trim().max(40),location:z.string().trim().max(120),coverLetter:z.string().trim().min(50).max(10000),portfolioUrl:safeUrlSchema.optional().or(z.literal("")),consent:z.literal("yes"),website:z.literal("")});
export async function POST(request:Request){const data=await request.formData();const parsed=fields.safeParse(Object.fromEntries([...data.entries()].filter(([key])=>key!=="cv")));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Check the application fields."},{status:400});const cv=data.get("cv");if(!(cv instanceof File)||!allowed.has(cv.type)||cv.size===0||cv.size>5*1024*1024)return NextResponse.json({error:"Upload a valid PDF, DOC or DOCX CV under 5 MB."},{status:400});const career=await prisma.career.findUnique({where:{id:parsed.data.careerId},select:{status:true,applicationDeadline:true}});if(!career||career.status!=="OPEN")return NextResponse.json({error:"This position is not accepting applications."},{status:409});if(career.applicationDeadline&&career.applicationDeadline<new Date())return NextResponse.json({error:"The application deadline has passed."},{status:409});const stored=await uploadFile({bytes:new Uint8Array(await cv.arrayBuffer()),originalName:cv.name,mimeType:cv.type,folder:"cvs",visibility:"private"});try{await prisma.jobApplication.create({data:{careerId:parsed.data.careerId,applicantName:parsed.data.applicantName,email:parsed.data.email,phone:parsed.data.phone||null,location:parsed.data.location||null,coverLetter:parsed.data.coverLetter,portfolioUrl:parsed.data.portfolioUrl||null,cvUrl:stored.key}});}catch(error){await deleteFile(stored.key).catch(()=>undefined);throw error;}return NextResponse.json({success:true},{status:201});}
