import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{companySlug:string}>}):Promise<Metadata>{
 const company=await prisma.company.findFirst({where:{slug:(await params).companySlug,status:"ACTIVE"},select:{name:true,summary:true,seoTitle:true,seoDescription:true,coverImageUrl:true}});
 if(!company)return{title:"Company Not Found"};return{title:company.seoTitle||company.name,description:company.seoDescription||company.summary,alternates:{canonical:`/companies/${(await params).companySlug}`},openGraph:{title:company.seoTitle||company.name,description:company.seoDescription||company.summary,images:company.coverImageUrl?[{url:company.coverImageUrl}]:undefined}};
}
export default async function CompanyPage({params}:{params:Promise<{companySlug:string}>}){
 const slug=(await params).companySlug;if(slug==="rfc")redirect("https://rfc-web-zeta.vercel.app/");if(slug==="smartcycle")redirect("https://smartcycle360.com");const company=await prisma.company.findFirst({where:{slug,status:"ACTIVE"},include:{projects:{where:{status:"PUBLISHED"},orderBy:{sortOrder:"asc"}},articles:{where:{status:"PUBLISHED"},orderBy:{publishedAt:"desc"},take:3},careers:{where:{status:"OPEN"},orderBy:{createdAt:"desc"}}}});if(!company)notFound();
 return <div className="company-profile-page"><section className="about-hero"><div className="section-container about-hero__container"><div className="about-hero__content"><p className="section-kicker">{company.industry||"BCU Group Company"}</p><h1>{company.name}</h1><p className="about-hero__lead">{company.summary}</p><Link className="button button--gold" href="/contact">Contact {company.shortName}</Link></div></div></section><section className="section"><div className="section-container"><div className="section-heading company-profile__long-heading"><p className="section-kicker">About</p><h2>{company.description}</h2></div></div></section><section className="section"><div className="section-container"><div className="section-header-row"><div className="section-heading"><p className="section-kicker">Portfolio</p><h2>Published projects</h2></div></div><div className="project-related-grid">{company.projects.map(project=><Link className="project-related-card" key={project.id} href={`/companies/${company.slug}/projects/${project.slug.replace(`${company.slug}-`,"")}`}><span>{project.category}</span><h3>{project.title}</h3><p>{project.summary}</p></Link>)}</div></div></section></div>;
}
