"use server";
import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { slugSchema } from "@/lib/validation";
import type { CompanyDTO } from "@/lib/company-service";
const schema=z.object({name:z.string().trim().min(2).max(160),slug:slugSchema,shortName:z.string().trim().min(1).max(40),summary:z.string().trim().min(10).max(600),description:z.string().trim().min(20).max(20000),logoUrl:z.string().trim().max(2048),coverImageUrl:z.string().trim().max(2048),websiteUrl:z.string().trim().url().optional().or(z.literal("")),email:z.string().trim().toLowerCase().email().optional().or(z.literal("")),phone:z.string().trim().max(50),location:z.string().trim().max(160),industry:z.string().trim().max(160),status:z.enum(["Draft","Active","Inactive","Archived"]),featured:z.boolean(),sortOrder:z.number().int().min(0),seoTitle:z.string().trim().max(70),seoDescription:z.string().trim().max(180)});
export type CompanyInput=z.input<typeof schema>;type Result={ok:true;id:string}|{ok:false;error:string;related?:CompanyDTO["related"]};
const mapStatus=(v:CompanyInput["status"])=>v==="Active"?"ACTIVE" as const:v==="Inactive"?"INACTIVE" as const:v==="Archived"?"ARCHIVED" as const:"DRAFT" as const;
function refresh(slug?:string){["/","/companies","/projects","/news","/careers","/admin","/admin/companies","/sitemap.xml"].forEach((path)=>revalidatePath(path));if(slug)revalidatePath(`/companies/${slug}`);}
export async function saveCompanyAction(id:string|null,input:CompanyInput):Promise<Result>{const user=await requireUser(["SUPER_ADMIN","ADMIN"]);const parsed=schema.safeParse(input);if(!parsed.success)return{ok:false,error:parsed.error.issues[0]?.message??"Invalid company."};const d=parsed.data;const data={name:d.name,slug:d.slug,shortName:d.shortName,summary:d.summary,description:d.description,logoUrl:d.logoUrl||null,coverImageUrl:d.coverImageUrl||null,websiteUrl:d.websiteUrl||null,email:d.email||null,phone:d.phone||null,location:d.location||null,industry:d.industry||null,status:mapStatus(d.status),featured:d.featured,sortOrder:d.sortOrder,seoTitle:d.seoTitle||null,seoDescription:d.seoDescription||null} satisfies Prisma.CompanyCreateInput;try{const old=id?await prisma.company.findUnique({where:{id},select:{slug:true}}):null;const saved=id?await prisma.company.update({where:{id},data}):await prisma.company.create({data});await prisma.auditLog.create({data:{userId:user.id,action:id?"UPDATE":"CREATE",entityType:"Company",entityId:saved.id,summary:`${id?"Updated":"Created"} ${saved.name}`}});refresh(saved.slug);if(old&&old.slug!==saved.slug)refresh(old.slug);return{ok:true,id:saved.id};}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")return{ok:false,error:"That company slug is already in use."};return{ok:false,error:"The company could not be saved."};}}
export async function deleteCompanyAction(id:string):Promise<Result>{const user=await requireUser(["SUPER_ADMIN","ADMIN"]);const row=await prisma.company.findUnique({where:{id},include:{_count:{select:{projects:true,articles:true,careers:true}}}});if(!row)return{ok:false,error:"Company not found."};const related={projects:row._count.projects,news:row._count.articles,careers:row._count.careers};if(Object.values(related).some(Boolean))return{ok:false,error:"Reassign or remove related records before deleting this company.",related};await prisma.$transaction([prisma.company.delete({where:{id}}),prisma.auditLog.create({data:{userId:user.id,action:"DELETE",entityType:"Company",entityId:id,summary:`Deleted ${row.name}`}})]);refresh(row.slug);return{ok:true,id};}
