"use server";
import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { slugSchema } from "@/lib/validation";
import { mapContentStatus } from "@/lib/content-status";

const schema=z.object({name:z.string().trim().min(2).max(180),slug:slugSchema,companyId:z.string().cuid(),category:z.string().trim().min(2).max(100),status:z.enum(["Draft","Published","Archived"]),summary:z.string().trim().min(10).max(600),description:z.string().trim().min(10).max(20000),coverImage:z.string().trim().max(2048),coverImageAlt:z.string().trim().max(240),featured:z.boolean(),tags:z.array(z.string().trim().min(1).max(50)).max(30),location:z.string().trim().max(160),startDate:z.string(),completionDate:z.string(),displayOrder:z.number().int().min(0),seoTitle:z.string().trim().max(70),seoDescription:z.string().trim().max(180)});
export type ProjectInput=z.input<typeof schema>;
type Result={ok:true;id:string}|{ok:false;error:string};
function refresh(slug?:string,companySlug?:string){revalidatePath("/");revalidatePath("/projects");revalidatePath("/admin");revalidatePath("/admin/projects");revalidatePath("/sitemap.xml");if(companySlug)revalidatePath(`/companies/${companySlug}`);if(slug&&companySlug)revalidatePath(`/companies/${companySlug}/projects/${slug}`);}
export async function saveProjectAction(id:string|null,input:ProjectInput):Promise<Result>{const user=await requireUser(["SUPER_ADMIN","ADMIN","EDITOR"]);const parsed=schema.safeParse(input);if(!parsed.success)return{ok:false,error:parsed.error.issues[0]?.message??"Invalid project."};const company=await prisma.company.findUnique({where:{id:parsed.data.companyId},select:{slug:true}});if(!company)return{ok:false,error:"Selected company does not exist."};const d=parsed.data;const data={title:d.name,slug:d.slug,companyId:d.companyId,category:d.category,status:mapContentStatus(d.status),summary:d.summary,description:{paragraphs:d.description.split(/\n\s*\n/).filter(Boolean)},coverImageUrl:d.coverImage||null,coverImageAlt:d.coverImageAlt||d.name,featured:d.featured,tags:d.tags,location:d.location||null,startDate:d.startDate?new Date(`${d.startDate}T00:00:00Z`):null,completionDate:d.completionDate?new Date(`${d.completionDate}T00:00:00Z`):null,sortOrder:d.displayOrder,seoTitle:d.seoTitle||null,seoDescription:d.seoDescription||null} satisfies Prisma.ProjectUncheckedCreateInput;try{const saved=id?await prisma.project.update({where:{id},data}):await prisma.project.create({data});await prisma.auditLog.create({data:{userId:user.id,action:id?"UPDATE":"CREATE",entityType:"Project",entityId:saved.id,summary:`${id?"Updated":"Created"} ${saved.title}`}});refresh(saved.slug.replace(`${company.slug}-`,""),company.slug);return{ok:true,id:saved.id};}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")return{ok:false,error:"That project slug is already in use."};return{ok:false,error:"The project could not be saved."};}}
export async function deleteProjectAction(id:string):Promise<Result>{const user=await requireUser(["SUPER_ADMIN","ADMIN","EDITOR"]);const row=await prisma.project.findUnique({where:{id},include:{company:{select:{slug:true}}}});if(!row)return{ok:false,error:"Project not found."};await prisma.$transaction([prisma.project.delete({where:{id}}),prisma.auditLog.create({data:{userId:user.id,action:"DELETE",entityType:"Project",entityId:id,summary:`Deleted ${row.title}`}})]);refresh(row.slug.replace(`${row.company.slug}-`,""),row.company.slug);return{ok:true,id};}
