import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
export const dynamic="force-dynamic";
const text=(value:Prisma.JsonValue)=>value&&typeof value==="object"&&!Array.isArray(value)&&"paragraphs" in value&&Array.isArray((value as {paragraphs?:unknown}).paragraphs)?((value as {paragraphs:string[]}).paragraphs):[];
async function find(companySlug:string,projectSlug:string){return prisma.project.findFirst({where:{status:"PUBLISHED",company:{slug:companySlug,status:"ACTIVE"},OR:[{slug:projectSlug},{slug:`${companySlug}-${projectSlug}`}]},include:{company:true}});}
export async function generateMetadata({params}:{params:Promise<{companySlug:string;projectSlug:string}>}):Promise<Metadata>{const p=await params;const project=await find(p.companySlug,p.projectSlug);if(!project)return{title:"Project Not Found"};return{title:project.seoTitle||project.title,description:project.seoDescription||project.summary,alternates:{canonical:`/companies/${p.companySlug}/projects/${p.projectSlug}`}};}
export default async function ProjectPage({params}:{params:Promise<{companySlug:string;projectSlug:string}>}){const p=await params;const project=await find(p.companySlug,p.projectSlug);if(!project)notFound();const related=await prisma.project.findMany({where:{companyId:project.companyId,status:"PUBLISHED",id:{not:project.id}},take:3,orderBy:{sortOrder:"asc"}});
return <div className="project-detail-page"><section className="project-detail-hero"><div className="section-container project-detail-hero__container"><div><Link className="project-detail-back" href={`/companies/${project.company.slug}`}>← Back to {project.company.shortName}</Link><div className="project-detail-meta"><span>{project.category}</span><span>{project.status}</span></div><h1>{project.title}</h1><p className="project-detail-summary">{project.summary}</p></div></div></section><section className="project-overview-section section"><div className="section-container project-overview-grid"><div className="section-heading"><p className="project-detail-eyebrow">Project Overview</p><h2>Designed for <span>practical impact.</span></h2></div><div className="project-overview-copy">{text(project.description).map((paragraph,index)=><p key={index}>{paragraph}</p>)}<div className="project-detail-tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></div></section><section className="related-projects-section section"><div className="section-container"><div className="project-related-grid">{related.map(item=><Link className="project-related-card" key={item.id} href={`/companies/${project.company.slug}/projects/${item.slug.replace(`${project.company.slug}-`,"")}`}><span>{item.category}</span><h3>{item.title}</h3><p>{item.summary}</p></Link>)}</div></div></section></div>;}
